### PR TITLE
Update setname and update location of mra

### PR DESCRIPTION
**Pull request by Toryalai1**
I updated the setname for the mras so that it follows MAME standard. This will also fix issues that we have in arcade organizer.

I also put the following files in an _alternatives folder:
_DoDonPachi/DoDonPachi (Trainer)
_DoDonPachi/DoDonPachi (Arrange)
_Guwange/Guwange(Special)

### CODE REVIEW

**Review by nullobject — COMMENTED** [review]
@Toryalai1 Hey, thanks for these updates.

What effect does moving MRA files to the `releases/_alternatives` directory have? Are they handled differently from just having them in the `releases` directory? (i.e. where do they end up on users' systems?)

**Comment by Toryalai1** [comment]
You are right, there is no reason to do that. I will try to revert that back.

**Comment by Toryalai1** [comment]
This should now be fixed. Sorry for the inconvinence

**Comment by nullobject** [comment]
> This should now be fixed. Sorry for the inconvenience

All good, thanks for the PR.

Happy to shuffle things around in the future if things change on the MiSTer :+1:

**Pull request merged**
