### PR TITLE
add ESP Ra.de. Free Play mra / Fix crc on Guwange special

### PR DESCRIPTION
**Pull request by terminator2k2**

### CODE REVIEW

**Review by nullobject — APPROVED** [review]
Thanks for these MRAs, much appreciated :heart:

**Comment by nullobject** [comment]
I pulled in the Guwange (Special) fix for the CRC values, thanks for that.

But I've been thinking I may start to move ROM hacks and bootlegs into the [MRA Alternatives](https://github.com/MiSTer-devel/MRA-Alternatives_MiSTer) repo. Do you know much about it?

**Comment by terminator2k2** [comment]
yes i think its a good idea to have the hacks sent to the mra alt repo, so you just have the official rom mra's on here. I will make a pull request for these 2 mra into the alt repo.

**Comment by nullobject** [comment]
Thanks, in that case I'm going to close this. Thanks again for the CRC fix in Guwange (Special).

**Pull request closed without merging**
